### ISSUE TITLE
Crash in Bannerlord v1.6.0 when starting a new game (campaign & sandbox) 

### ISSUE THREAD

**Issue by mrgswift** [ashakoor/UnlimitLord#14]
When I try to create a new game in sandbox or campaign, the game crashes.  It looks like something isn't working correctly during the character creation routine after clicking "Start Game"

I verified it was the UnlimitLord mod causing the problem by installing a new vanilla copy of Bannerlord with only UnlimitLord and its required mods. When I disable the UnlimitLord mod in the launch screen, the game loads into the map successfully with the new character without crashing.   Thank you for all of the work you have put into this mod, it is much appreciated!!!

**Mods Installed and launched in this order**

Harmony **v2.1.1.65**
ButterLib  **v1.0.27**
UiExtenderEx **v2.1.6**
ModConfigurationMenu  **v4.3.14**
Native **v1.6.0**
SandboxCore **v1.6.0**
Sandbox **v1.6.0**
CustomBattle **v1.6.0**
StoryMode **v1.6.0**
UnlimitLord **v0.5.0**

**Stack Trace from log:**

```
[14:24:14.538]  

[14:24:14.540] ActiveStateDisabledByUser being set to: False 

[14:24:14.553] Force VSync State is now DEACTIVATED 

[14:24:14.553] CleanAndPushScreen 

[14:24:14.553] SandBox.View.CharacterCreation.CharacterCreationScreen::HandlePause 

[14:24:14.553] SandBox.View.CharacterCreation.CharacterCreationScreen::HandleDeactivate 

[14:24:14.553] SandBox.View.CharacterCreation.CharacterCreationScreen::HandleFinalize 

[14:24:14.554] Scene_view::clear_all(character_menu_new)
[14:24:14.599] SandBox.View.Map.MapScreen::HandleInitialize 

**[14:24:14.884] Exception occurred inside invoke: OnNextStage
Target type: TaleWorlds.CampaignSystem.ViewModelCollection.CharacterCreation.OptionsStage.CharacterCreationOptionsStageVM
Argument count: 0
Inner message: Object reference not set to an instance of an object.** 

[14:24:14.895] 
<##########################################################################################>

[14:24:14.895] #kernelbase.pdb@{993F0EEA8C3C260F6D52724A7CA16660} (1): 0:277273
#clr.pdb@{20373C0156BD497E8BF052933B09D156} (2): 0:1504945
#clr.pdb@{20373C0156BD497E8BF052933B09D156} (2): 0:1909495
@unknown_module@unknown_source (unknown_line): unknown_function
#clr.pdb@{20373C0156BD497E8BF052933B09D156} (2): 0:1503302
#clr.pdb@{20373C0156BD497E8BF052933B09D156} (2): 0:1503004
#clr.pdb@{20373C0156BD497E8BF052933B09D156} (2): 0:1502750
#ntdll.pdb@{27341C1B9147DD100EC194BFDD47B97A} (1): 0:663679
#ntdll.pdb@{27341C1B9147DD100EC194BFDD47B97A} (1): 0:121266
#clr.pdb@{20373C0156BD497E8BF052933B09D156} (2): 0:1507292
#clr.pdb@{20373C0156BD497E8BF052933B09D156} (2): 0:1507224
#ntdll.pdb@{27341C1B9147DD100EC194BFDD47B97A} (1): 0:663551
#ntdll.pdb@{27341C1B9147DD100EC194BFDD47B97A} (1): 0:436953
#ntdll.pdb@{27341C1B9147DD100EC194BFDD47B97A} (1): 0:436371
#kernelbase.pdb@{993F0EEA8C3C260F6D52724A7CA16660} (1): 0:277273
#clr.pdb@{20373C0156BD497E8BF052933B09D156} (2): 0:1504945
#clr.pdb@{20373C0156BD497E8BF052933B09D156} (2): 0:2074333
#clr.pdb@{20373C0156BD497E8BF052933B09D156} (2): 0:2074499
#clr.pdb@{20373C0156BD497E8BF052933B09D156} (2): 0:2074512
#clr.pdb@{20373C0156BD497E8BF052933B09D156} (2): 0:6582401
#clr.pdb@{20373C0156BD497E8BF052933B09D156} (2): 0:3767632
#mscorlib.pdb@{C027B9A30C9045F9A60BFDA221B43D4F} (2): 0:5888269
#mscorlib.pdb@{C027B9A30C9045F9A60BFDA221B43D4F} (2): 0:5984754
@unknown_module@unknown_source (unknown_line): unknown_function
@unknown_module@unknown_source (unknown_line): unknown_function
@unknown_module@unknown_source (unknown_line): unknown_function
@unknown_module@unknown_source (unknown_line): unknown_function
@unknown_module@unknown_source (unknown_line): unknown_function
@unknown_module@unknown_source (unknown_line): unknown_function
@unknown_module@unknown_source (unknown_line): unknown_function
@unknown_module@unknown_source (unknown_line): unknown_function
@unknown_module@unknown_source (unknown_line): unknown_function
@unknown_module@unknown_source (unknown_line): unknown_function
@unknown_module@unknown_source (unknown_line): unknown_function
#clr.pdb@{20373C0156BD497E8BF052933B09D156} (2): 0:8734
#TaleWorlds.Native.pdb@{1AA2F91A53F04AA2BB7952B4CEA4E2C6} (1): 0:5061322
#TaleWorlds.Native.pdb@{1AA2F91A53F04AA2BB7952B4CEA4E2C6} (1): 0:322287
#TaleWorlds.Native.pdb@{1AA2F91A53F04AA2BB7952B4CEA4E2C6} (1): 0:319426
#TaleWorlds.Native.pdb@{1AA2F91A53F04AA2BB7952B4CEA4E2C6} (1): 0:270484
#TaleWorlds.Native.pdb@{1AA2F91A53F04AA2BB7952B4CEA4E2C6} (1): 0:2093015
#TaleWorlds.Native.pdb@{1AA2F91A53F04AA2BB7952B4CEA4E2C6} (1): 0:2092283
#TaleWorlds.Native.pdb@{1AA2F91A53F04AA2BB7952B4CEA4E2C6} (1): 0:2096263
#ucrtbase.pdb@{E2955775A9DDACFAD2742EB16FBCAA39} (1): 0:135346
#kernel32.pdb@{DE3AF594A0A42F82A264E8D2CDC47B4C} (1): 0:97316
#ntdll.pdb@{27341C1B9147DD100EC194BFDD47B97A} (1): 0:448289
-----------------------------------------------
at TaleWorlds.DotNet.Managed.GetStackTraceStr(Int32 skipCount)
at TaleWorlds.Library.Common.InvokeWithLog(MethodInfo methodInfo, Object obj, Object[] args)
at TaleWorlds.Library.ViewModel.ExecuteCommand_Patch1(ViewModel this, String commandName, Object[] parameters)
at TaleWorlds.GauntletUI.Data.GauntletView.OnCommand_Patch0(GauntletView this, String command, Object[] args)
at TaleWorlds.GauntletUI.Widget.EventFired(String eventName, Object[] args)
at TaleWorlds.GauntletUI.ButtonWidget.HandleClick()
at TaleWorlds.GauntletUI.ButtonWidget.OnMouseReleased()
at TaleWorlds.GauntletUI.EventManager.MouseUp()
at TaleWorlds.GauntletUI.UIContext.UpdateInput(InputType handleInputs)
at TaleWorlds.Engine.Screens.ScreenManager.Update()
at TaleWorlds.Engine.Screens.ScreenManager.Tick(Single dt)
```

**Comment by Cytraen** [comment]
Hey, sorry for the wait. e1.6.0 has some breaking changes which I haven't been able to get around to yet. I'll take a look when possible. Thanks for using UnlimitLord and for letting me know!

**Comment by mrgswift** [comment]
@ashakoor It looks like they already updated the game to e1.6.1 in Steam, so I guess at this point the information I gave in this Github issue may no longer be helpful.
